{{- if and .Values.frontendUi.enabled .Values.frontendUi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubechan.fullname" . }}-frontend-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubechan.labels" . | nindent 4 }}
    kubechan.io/component: frontend-ui
  {{- with .Values.frontendUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontendUi.ingress.className }}
  ingressClassName: {{ .Values.frontendUi.ingress.className | quote }}
  {{- end }}
  {{- if .Values.frontendUi.ingress.tls }}
  tls:
    {{- toYaml .Values.frontendUi.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.frontendUi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "kubechan.fullname" $ }}-frontend-ui
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
