apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubechan.fullname" . }}-diagnostics-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubechan.labels" . | nindent 4 }}
    kubechan.io/component: diagnostics-worker
